version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    platform: linux/arm64
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - 3336:3306
    expose:
      - 3336
    volumes:
      - ./data/mysql:/var/lib/mysql
  fastfoodservice:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306